version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.16.0-browsers
    steps:
      - checkout

      - run: export IS_CIRCLE=true
      - run: node --version
      - run: npm --version
      - run: yarn --version
      - run: google-chrome --version

      - run: cd chapter08 && yarn install
      - run: cd chapter08 && yarn run webdriver-circle
      - run: cd chapter08 && xvfb-run -a yarn run e2e protractor-first-test.conf.js
      - run: cd chapter08 && xvfb-run -a yarn run e2e protractor-add-contact.conf.js
      - run: cd chapter08 && xvfb-run -a yarn run e2e protractor-invalid-contact.conf.js
      - run: cd chapter08 && xvfb-run -a yarn run e2e protractor-contact-list.conf.js
      - run: cd chapter08 && xvfb-run -a yarn run e2e protractor-page-objects.conf.js
      - run: cd chapter08 && xvfb-run -a yarn run e2e protractor-tables.conf.js

      - run: cd chapter09 && yarn install
      - run: cd chapter09 && yarn run webdriver-circle
      - run: cd chapter09 && xvfb-run -a yarn run e2e

      - run: cd chapter10/test_capabilities && yarn install
      - run: cd chapter10/test_capabilities && yarn run webdriver-circle
      - run: cd chapter10/test_capabilities && yarn run e2e protractor.conf.js
      - run: cd chapter10/test_multicapabilities && yarn install
      - run: cd chapter10/test_multicapabilities && yarn run webdriver-circle
      - run: cd chapter10/test_multicapabilities && yarn run e2e protractor-chrome.conf.js
      - run: cd chapter10/test_plugins && yarn install
      - run: cd chapter10/test_plugins && yarn run webdriver-circle
      - run: cd chapter10/test_plugins && yarn run e2e protractor-onprepare-method.conf.js
      - run: cd chapter10/test_plugins && yarn run e2e protractor-onprepare-plugin.conf.js

      - run: cd chapter11 && ./run_unit_ci.sh
